[envs.default]
dependencies = [
  'coverage[toml]>=6.2',
  'pytest',
  'pytest-cov',
  'pytest-mock',
]
post-install-commands = [
  'python -m pip install -q -e ../hatch',
]
[envs.default.scripts]
full = 'pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=hatch_containers --cov=tests'
no-cov = 'pytest --no-cov'

[envs.lint]
skip-install = true
dependencies = [
  'flake8~=3.9',
  'flake8-bugbear~=21.4',
  'flake8-quotes~=3.2',
  'black~=21.12b0',
  'isort~=5.8',
  'mypy==0.920',
]
[envs.lint.scripts]
typing = 'mypy --install-types --non-interactive hatch_containers tests'
style = [
  'flake8 .',
  'black --check --diff .',
  'isort --check-only --diff .',
]
fmt = [
  'isort .',
  'black .',
  'style',
]
all = [
  'style',
  # 'typing',
]
